apiVersion: v1
kind: Service
metadata:
  name: chatroom-app
  namespace: chatroom
  labels:
    app.kubernetes.io/name: chatroom
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: chatroom
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
