#!/usr/bin/env bash
# set_mysql_host.sh
# -----------------------------------------------------------------------------
# Script to manually set the MySQL host in .env.runtime for custom deployment scenarios.
# This allows users to override the automatically generated MYSQL_HOST=mysql value.
# -----------------------------------------------------------------------------

set -euo pipefail

# Default values
DEFAULT_ENV_FILE="$REPO_ROOT/app/.env.runtime"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Validate usage
if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <mysql-host>" >&2
    exit 1
fi

MYSQL_HOST="$1"

# Validate input
if [[ -z "$MYSQL_HOST" ]]; then
    echo "Error: MySQL host cannot be empty" >&2
    exit 1
fi

# Check if .env.runtime exists
if [[ ! -f "$DEFAULT_ENV_FILE" ]]; then
    echo "Error: $DEFAULT_ENV_FILE does not exist" >&2
    echo "Run 'scripts/build_images.sh' first to generate it" >&2
    exit 1
fi

# Read the current environment file
ENV_CONTENT=$(cat "$DEFAULT_ENV_FILE")

# Check if MYSQL_HOST is already set
if [[ "$ENV_CONTENT" == *"MYSQL_HOST="* ]]; then
    # Replace existing MySQL_HOST line or add new one
    if [[ "$ENV_CONTENT" == *"# Generated by "* && "$ENV_CONTENT" == *"MYSQL_HOST="* ]]; then
        # It's in the generated section, so replace it
        NEW_ENV_CONTENT=$(echo "$ENV_CONTENT" | sed "s/^MYSQL_HOST=.*$/MYSQL_HOST=$MYSQL_HOST/")
    else
        # It's not in the generated section, so we need to add it
        NEW_ENV_CONTENT=$(echo "$ENV_CONTENT" | sed "/^# Generated by/d")
        NEW_ENV_CONTENT+=$'\n'"MYSQL_HOST=$MYSQL_HOST"$'\n'"# Generated by set_mysql_host.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    fi

    # Write the updated content back
    TMP_ENV=$(mktemp "$DEFAULT_ENV_FILE.XXXXXX")
    echo "$NEW_ENV_CONTENT" > "$TMP_ENV"
    mv "$TMP_ENV" "$DEFAULT_ENV_FILE"
    chmod 600 "$DEFAULT_ENV_FILE"
    echo "Updated $DEFAULT_ENV_FILE with MySQL host: $MYSQL_HOST"
else
    # No MYSQL_HOST line found, add it to the end
    TMP_ENV=$(mktemp "$DEFAULT_ENV_FILE.XXXXXX")
    echo "$ENV_CONTENT" > "$TMP_ENV"
    echo "MYSQL_HOST=$MYSQL_HOST" >> "$TMP_ENV"
    echo "# Generated by set_mysql_host.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$TMP_ENV"
    mv "$TMP_ENV" "$DEFAULT_ENV_FILE"
    chmod 600 "$DEFAULT_ENV_FILE"
    echo "Added MySQL host to $DEFAULT_ENV_FILE: $MYSQL_HOST"
fi

echo "Successfully set MySQL host in $DEFAULT_ENV_FILE"